version: '2'
services:
  octoprint:
    build: .
#    image: octoprint/octoprint
    container_name: octoprint
    environment:
      BALENA_MACHINE_NAME: %%BALENA_MACHINE_NAME%%
    ports:
      - 5000:5000
    # devices:
    #  - /dev/ttyACM0:/dev/ttyACM0
#    volumes:
#     - ./config:/home/octoprint/.octoprint
